name: cuda121
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.6.2=py310h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.0.4=0
  - libcurand=10.3.6.39=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_1
  - openssl=3.0.14=h5eee18b_0
  - pillow=10.3.0=py310h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - pytorch=2.3.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py310h06a4308_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py310_cu121
  - torchvision=0.18.1=py310_cu121
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.2=py310h06a4308_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anyio==4.4.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astor==0.8.1
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - awkward==2.6.6
      - awkward-cpp==35
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bio==1.7.1
      - biopython==1.84
      - biothings-client==0.3.1
      - bleach==6.1.0
      - cffi==1.16.0
      - cloudpickle==3.0.0
      - cmake==3.30.0
      - colorama==0.4.6
      - comm==0.2.2
      - cramjam==2.8.3
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - einops==0.8.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.11.0
      - flash-attn==2.5.9.post1
      - flexcache==0.3
      - flexparser==0.3.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - fvcore==0.1.5.post20221221
      - gprofiler-official==1.0.0
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - importlib-metadata==8.0.0
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.26.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.4.2
      - json-tricks==3.17.3
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - lightning-utilities==0.11.3.post0
      - llvmlite==0.43.0
      - markdown==3.6
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - multidict==6.0.5
      - mygene==3.2.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - nni==3.0
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - nvidia-ml-py==12.555.43
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pint==0.24.1
      - platformdirs==4.2.2
      - pooch==1.8.2
      - portalocker==2.10.0
      - prettytable==3.10.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pythonwebhdfs==0.2.3
      - pytz==2024.1
      - pyzmq==26.0.3
      - rdkit==2024.3.3
      - referencing==0.35.1
      - responses==0.25.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - schema==0.7.7
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - send2trash==1.8.3
      - simplejson==3.19.2
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torchmetrics==1.4.0.post0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - triton==2.3.1
      - typeguard==4.1.2
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - uproot==5.3.9
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.0.3
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.19.2
prefix: /usr/scratch/smiao35/anaconda3/envs/cuda121
# pip install torch_geometric==2.5.3
# pip install torch_scatter==2.1.2 torch_cluster==1.6.3 -f https://data.pyg.org/whl/torch-2.3.0+cu121.html